---
name: Coverage
on: [push]
permissions: read-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64-coverage
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          mkdir "${TARGET}"
          case "${TARGET}" in
            linux-amd64-coverage)
              GOARCH=amd64 ./scripts/codecov_upload.sh
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
