---
name: Reusable Arm64 E2E Workflow
on:
  workflow_call:
    inputs:
      etcdBranch:
        required: true
        type: string
permissions: read-all
jobs:
  test:
    # this is to prevent the job to run at forked projects
    if: github.repository == 'etcd-io/etcd'
    runs-on: actuated-arm64-8cpu-32gb
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-arm64-e2e
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          ref: "${{ inputs.etcdBranch }}"
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          set -euo pipefail
          go clean -testcache

          echo "${TARGET}"
          case "${TARGET}" in
            linux-arm64-e2e)
              GOOS=linux GOARCH=arm64 CPU=4 EXPECT_DEBUG=true make test-e2e-release
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
