---
name: Static Analysis
on: [push, pull_request]
permissions: read-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.55.2
          args: --config tools/.golangci.yaml
      - name: protoc
        uses: arduino/setup-protoc@a8b67ba40b37d35169e222f3bb352603327985b6 # v2.1.0
        with:
          version: '3.20.3'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          set -euo pipefail

          cargo install marker --version 0.9.0
      - run: |
          set -euo pipefail

          make verify
      - run: |
          set -euo pipefail

          make fix

          DIFF=$(git status --porcelain)

          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
